af= "spesso ciò che è temporaneo diventa definitivo"
print(af)
print(af.replace(" ", "_"))
print(af.lower())
print(af.upper())
print(af.split())
print(af.count("e"))
print(f"la frase del giorno è lunga {len(af)}  caratteri ")
print(af[10])
print(af[0])
print(af[38])
print(af[-6])
print(af[0:4])
print(af[-5:-1])
print(af[-10:])